//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string City { get; set; }
        public string ClientInformation { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
        public string District { get; set; }
        public System.Guid Id { get; set; }
        public string Ip { get; set; }
        public string Isp { get; set; }
        public string Province { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Type { get; set; }
    }
}
